# Generated by Django 4.2.17 on 2024-12-20 13:43

import datetime
from decimal import Decimal
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Onderwerp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "gepubliceerd",
                    models.BooleanField(
                        default=False,
                        help_text="Geeft aan of het object getoond kan worden.",
                        verbose_name="gepubliceerd",
                    ),
                ),
                (
                    "aanmaak_datum",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="De datum waarop het object is aangemaakt.",
                        verbose_name="Created on",
                    ),
                ),
                (
                    "update_datum",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="De datum waarop het object voor het laatst is gewijzigd.",
                        verbose_name="Updated on",
                    ),
                ),
                (
                    "naam",
                    models.CharField(
                        help_text="Naam van het onderwerp.",
                        max_length=100,
                        verbose_name="naam",
                    ),
                ),
                (
                    "beschrijving",
                    markdownx.models.MarkdownxField(
                        blank=True,
                        default="",
                        help_text="Beschrijving van het onderwerp, ondersteund markdown format.",
                        verbose_name="beschrijving",
                    ),
                ),
                (
                    "hoofd_onderwerp",
                    models.ForeignKey(
                        blank=True,
                        help_text="Het hoofd onderwerp van het onderwerp.",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="sub_onderwerpen",
                        to="producttypen.onderwerp",
                        verbose_name="hoofd onderwerp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Onderwerp",
                "verbose_name_plural": "Onderwerpen",
            },
        ),
        migrations.CreateModel(
            name="Prijs",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "actief_vanaf",
                    models.DateField(
                        help_text="De datum vanaf wanneer de prijs actief is.",
                        validators=[
                            django.core.validators.MinValueValidator(
                                datetime.date.today
                            )
                        ],
                        verbose_name="start datum",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prijs",
                "verbose_name_plural": "Prijzen",
            },
        ),
        migrations.CreateModel(
            name="ProductType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "gepubliceerd",
                    models.BooleanField(
                        default=False,
                        help_text="Geeft aan of het object getoond kan worden.",
                        verbose_name="gepubliceerd",
                    ),
                ),
                (
                    "aanmaak_datum",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="De datum waarop het object is aangemaakt.",
                        verbose_name="Created on",
                    ),
                ),
                (
                    "update_datum",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="De datum waarop het object voor het laatst is gewijzigd.",
                        verbose_name="Updated on",
                    ),
                ),
                (
                    "naam",
                    models.CharField(
                        help_text="naam van het product type.",
                        max_length=100,
                        verbose_name="product type naam",
                    ),
                ),
                (
                    "samenvatting",
                    models.TextField(
                        default="",
                        help_text="Korte beschrijving van het product type, maximaal 300 karakters.",
                        max_length=300,
                        verbose_name="samenvatting",
                    ),
                ),
                (
                    "beschrijving",
                    markdownx.models.MarkdownxField(
                        help_text="Product type beschrijving, ondersteund markdown format.",
                        verbose_name="beschrijving",
                    ),
                ),
                (
                    "keywords",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=100),
                        blank=True,
                        default=list,
                        help_text="Lijst van keywords waarop kan worden gezocht.",
                        size=None,
                        verbose_name="Keywords",
                    ),
                ),
                (
                    "onderwerpen",
                    models.ManyToManyField(
                        blank=True,
                        help_text="onderwerpen waaraan het product type is gelinkt.",
                        related_name="product_typen",
                        to="producttypen.onderwerp",
                        verbose_name="onderwerp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product type",
                "verbose_name_plural": "Product typen",
            },
        ),
        migrations.CreateModel(
            name="UniformeProductNaam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "naam",
                    models.CharField(
                        help_text="Uniforme product naam",
                        max_length=100,
                        unique=True,
                        verbose_name="naam",
                    ),
                ),
                (
                    "uri",
                    models.URLField(
                        help_text="Uri naar de UPN definitie.",
                        unique=True,
                        verbose_name="Uri",
                    ),
                ),
                (
                    "is_verwijderd",
                    models.BooleanField(
                        default=False,
                        help_text="Geeft aan of de UPN is verwijderd.",
                        verbose_name="is verwijderd",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uniforme product naam",
                "verbose_name_plural": "Uniforme product namen",
            },
        ),
        migrations.CreateModel(
            name="Vraag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "vraag",
                    models.CharField(
                        help_text="De vraag die wordt beantwoord.",
                        max_length=250,
                        verbose_name="vraag",
                    ),
                ),
                (
                    "antwoord",
                    markdownx.models.MarkdownxField(
                        help_text="Het antwoord op de vraag, ondersteund markdown format.",
                        verbose_name="antwoord",
                    ),
                ),
                (
                    "onderwerp",
                    models.ForeignKey(
                        blank=True,
                        help_text="Het onderwerp waarbij deze vraag hoort.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vragen",
                        to="producttypen.onderwerp",
                        verbose_name="onderwerp",
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Het product type waarbij deze vraag hoort.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vragen",
                        to="producttypen.producttype",
                        verbose_name="Product type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vraag",
                "verbose_name_plural": "Vragen",
            },
        ),
        migrations.AddField(
            model_name="producttype",
            name="uniforme_product_naam",
            field=models.ForeignKey(
                help_text="Uniforme product naam gedefinieerd door de overheid.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_typen",
                to="producttypen.uniformeproductnaam",
                verbose_name="Uniforme Product naam",
            ),
        ),
        migrations.CreateModel(
            name="PrijsOptie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "bedrag",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Het bedrag van de prijs optie.",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="bedrag",
                    ),
                ),
                (
                    "beschrijving",
                    models.CharField(
                        help_text="Korte beschrijving van de optie.",
                        max_length=100,
                        verbose_name="beschrijving",
                    ),
                ),
                (
                    "prijs",
                    models.ForeignKey(
                        help_text="De prijs waarbij deze optie hoort.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prijsopties",
                        to="producttypen.prijs",
                        verbose_name="prijs",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prijs optie",
                "verbose_name_plural": "Prijs opties",
            },
        ),
        migrations.AddField(
            model_name="prijs",
            name="product_type",
            field=models.ForeignKey(
                help_text="Het product type waarbij deze prijs hoort.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prijzen",
                to="producttypen.producttype",
                verbose_name="product type",
            ),
        ),
        migrations.CreateModel(
            name="OnderwerpProductType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "onderwerp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="producttypen.onderwerp",
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="producttypen.producttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "naam",
                    models.CharField(
                        help_text="Naam van de link.",
                        max_length=100,
                        verbose_name="naam",
                    ),
                ),
                (
                    "url",
                    models.URLField(help_text="Url van de link.", verbose_name="Url"),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        help_text="Het product type waarbij deze link hoort.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="producttypen.producttype",
                        verbose_name="Product type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product type link",
                "verbose_name_plural": "Product type links",
            },
        ),
        migrations.CreateModel(
            name="Bestand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bestand", models.FileField(upload_to="", verbose_name="bestand")),
                (
                    "product_type",
                    models.ForeignKey(
                        help_text="Het product type waarbij dit bestand hoort.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bestanden",
                        to="producttypen.producttype",
                        verbose_name="product type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product type bestand",
                "verbose_name_plural": "Product type bestanden",
            },
        ),
        migrations.AlterUniqueTogether(
            name="prijs",
            unique_together={("product_type", "actief_vanaf")},
        ),
    ]
