# Generated by Django 4.2.17 on 2024-12-24 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("producttypen", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OnderwerpProductType",
        ),
    ]
