# Generated by Django 4.2.17 on 2024-12-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producttypen", "0002_producttype_contacten_producttype_locaties_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttype",
            name="code",
            field=models.CharField(
                help_text="code van het product type.",
                max_length=100,
                unique=True,
                verbose_name="code",
            ),
        ),
    ]
