# Generated by Django 4.2.17 on 2024-12-27 12:11

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("producttypen", "0002_delete_onderwerpproducttype"),
    ]

    operations = [
        migrations.CreateModel(
            name="Thema",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "gepubliceerd",
                    models.BooleanField(
                        default=False,
                        help_text="Geeft aan of het object getoond kan worden.",
                        verbose_name="gepubliceerd",
                    ),
                ),
                (
                    "aanmaak_datum",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="De datum waarop het object is aangemaakt.",
                        verbose_name="Created on",
                    ),
                ),
                (
                    "update_datum",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="De datum waarop het object voor het laatst is gewijzigd.",
                        verbose_name="Updated on",
                    ),
                ),
                (
                    "naam",
                    models.CharField(
                        help_text="Naam van het thema.",
                        max_length=100,
                        verbose_name="naam",
                    ),
                ),
                (
                    "beschrijving",
                    markdownx.models.MarkdownxField(
                        blank=True,
                        default="",
                        help_text="Beschrijving van het thema, ondersteund markdown format.",
                        verbose_name="beschrijving",
                    ),
                ),
                (
                    "hoofd_thema",
                    models.ForeignKey(
                        blank=True,
                        help_text="Het hoofd thema van het thema.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sub_themas",
                        to="producttypen.thema",
                        verbose_name="hoofd thema",
                    ),
                ),
            ],
            options={
                "verbose_name": "thema",
                "verbose_name_plural": "thema's",
            },
        ),
        migrations.RemoveField(
            model_name="producttype",
            name="onderwerpen",
        ),
        migrations.RemoveField(
            model_name="vraag",
            name="onderwerp",
        ),
        migrations.DeleteModel(
            name="Onderwerp",
        ),
        migrations.AddField(
            model_name="producttype",
            name="themas",
            field=models.ManyToManyField(
                blank=True,
                help_text="thema's waaraan het product type is gelinkt.",
                related_name="product_typen",
                to="producttypen.thema",
                verbose_name="thema's",
            ),
        ),
        migrations.AddField(
            model_name="vraag",
            name="thema",
            field=models.ForeignKey(
                blank=True,
                help_text="Het thema waarbij deze vraag hoort.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vragen",
                to="producttypen.thema",
                verbose_name="thema",
            ),
        ),
    ]
