# Generated by Django 4.2.17 on 2024-12-13 16:21

from django.db import migrations, models
import open_producten.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("producttypen", "0003_producttype_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttype",
            name="toegestane_statussen",
            field=open_producten.utils.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("gereed", "Gereed"),
                        ("actief", "Actief"),
                        ("ingetrokken", "Ingetrokken"),
                        ("geweigerd", "Geweigerd"),
                        ("verlopen", "Verlopen"),
                    ]
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
