# Generated by Django 4.2.17 on 2025-01-27 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("django_json_schema_model", "0001_initial"),
        ("producttypen", "0004_producttype_contacten_producttype_locaties_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttype",
            name="verbruiksobject_schema",
            field=models.ForeignKey(
                blank=True,
                help_text="JSON schema om het verbruiksobject van een gerelateerd product te valideren.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_typen",
                to="django_json_schema_model.jsonschema",
                verbose_name="verbruiksobject schema",
            ),
        ),
    ]
