# Generated by Django 4.2.17 on 2024-12-17 10:25

from django.db import migrations, models
import open_producten.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("producttypen", "0004_producttype_toegestane_statussen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producttype",
            name="toegestane_statussen",
            field=open_producten.utils.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("gereed", "Gereed"),
                        ("actief", "Actief"),
                        ("ingetrokken", "Ingetrokken"),
                        ("geweigerd", "Geweigerd"),
                        ("verlopen", "Verlopen"),
                    ]
                ),
                blank=True,
                default=list,
                help_text="toegestane statussen voor producten van dit type.",
                size=None,
                verbose_name="toegestane statussen",
            ),
        ),
    ]
