# Generated by Django 4.2.17 on 2024-12-30 14:12

from django.db import migrations, models
import open_producten.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("producttypen", "0004_producttype_contacten_producttype_locaties_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttype",
            name="code",
            field=models.CharField(
                help_text="code van het product type.",
                max_length=100,
                unique=True,
                verbose_name="code",
            ),
        ),
        migrations.AddField(
            model_name="producttype",
            name="toegestane_statussen",
            field=open_producten.utils.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("gereed", "Gereed"),
                        ("actief", "Actief"),
                        ("ingetrokken", "Ingetrokken"),
                        ("geweigerd", "Geweigerd"),
                        ("verlopen", "Verlopen"),
                    ]
                ),
                blank=True,
                default=list,
                help_text="toegestane statussen voor producten van dit type.",
                size=None,
                verbose_name="toegestane statussen",
            ),
        ),
    ]
