# Generated by Django 4.2.17 on 2025-02-06 10:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        (
            "producttypen",
            "0005_producttype_code_producttype_toegestane_statussen_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Eigenschap",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="De sleutel van de eigenschap",
                        max_length=255,
                        unique=True,
                        verbose_name="key",
                    ),
                ),
                (
                    "waarde",
                    models.CharField(
                        help_text="De waarde van de eigenschap",
                        max_length=255,
                        unique=True,
                        verbose_name="waarde",
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        help_text="Het product type waarbij deze eigenschap hoort.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eigenschappen",
                        to="producttypen.producttype",
                        verbose_name="product type",
                    ),
                ),
            ],
            options={
                "verbose_name": "eigenschap",
                "verbose_name_plural": "eigenschappen",
            },
        ),
    ]
