# Generated by Django 4.2.17 on 2025-02-06 10:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        (
            "producttypen",
            "0005_producttype_code_producttype_toegestane_statussen_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PrijsRegel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "beschrijving",
                    models.CharField(
                        help_text="Korte beschrijving van de prijs regel en dmn tabel.",
                        max_length=255,
                        verbose_name="beschrijving",
                    ),
                ),
                (
                    "dmn_url",
                    models.URLField(
                        help_text="Url om de dmn tabel te evalueren",
                        verbose_name="dmn url",
                    ),
                ),
                (
                    "prijs",
                    models.ForeignKey(
                        help_text="De prijs waarbij deze regel hoort.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prijsregels",
                        to="producttypen.prijs",
                        verbose_name="prijs",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prijs regel",
                "verbose_name_plural": "Prijs regels",
            },
        ),
    ]
