# Generated by Django 4.2.17 on 2025-02-07 11:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        (
            "producttypen",
            "0005_producttype_code_producttype_toegestane_statussen_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ExterneCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "naam",
                    models.CharField(
                        help_text="De naam van het systeem van de externe product code.",
                        max_length=255,
                        verbose_name="naam",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="De code van de van het product type in het externe systeem.",
                        max_length=255,
                        verbose_name="code",
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        help_text="Het product type waarbij deze externe code hoort.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="externe_codes",
                        to="producttypen.producttype",
                        verbose_name="product type",
                    ),
                ),
            ],
            options={
                "verbose_name": "externe product type code",
                "verbose_name_plural": "externe product type codes",
                "unique_together": {("product_type", "naam")},
            },
        ),
        migrations.CreateModel(
            name="Eigenschap",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "naam",
                    models.CharField(
                        help_text="De naam van de eigenschap",
                        max_length=255,
                        verbose_name="naam",
                    ),
                ),
                (
                    "waarde",
                    models.CharField(
                        help_text="De waarde van de eigenschap",
                        max_length=255,
                        verbose_name="waarde",
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        help_text="Het product type waarbij deze eigenschap hoort.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eigenschappen",
                        to="producttypen.producttype",
                        verbose_name="product type",
                    ),
                ),
            ],
            options={
                "verbose_name": "eigenschap",
                "verbose_name_plural": "eigenschappen",
                "unique_together": {("product_type", "naam")},
            },
        ),
    ]
