# Generated by Django 4.2.17 on 2025-02-06 15:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("producttypen", "0006_eigenschap"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eigenschap",
            name="key",
            field=models.CharField(
                help_text="De sleutel van de eigenschap",
                max_length=255,
                verbose_name="key",
            ),
        ),
        migrations.AlterField(
            model_name="eigenschap",
            name="waarde",
            field=models.CharField(
                help_text="De waarde van de eigenschap",
                max_length=255,
                verbose_name="waarde",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eigenschap",
            unique_together={("product_type", "key")},
        ),
        migrations.CreateModel(
            name="ExterneCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "systeem",
                    models.CharField(
                        help_text="De systeem van de externe product code",
                        max_length=255,
                        verbose_name="systeem",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="De code van de van het product type in het systeem",
                        max_length=255,
                        verbose_name="code",
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        help_text="Het product type waarbij deze externe code hoort.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="externe_codes",
                        to="producttypen.producttype",
                        verbose_name="product type",
                    ),
                ),
            ],
            options={
                "verbose_name": "externe product type code",
                "verbose_name_plural": "externe product type codes",
                "unique_together": {("product_type", "systeem")},
            },
        ),
    ]
