# Generated by Django 4.2.17 on 2025-01-19 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("django_json_schema_model", "0001_initial"),
        ("producttypen", "0006_producttype_verbruiksobject_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttype",
            name="dataobject_schema",
            field=models.ForeignKey(
                blank=True,
                help_text="JSON schema om het dataobject van een gerelateerd product te valideren.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_typen_dataobject_schemas",
                to="django_json_schema_model.jsonschema",
                verbose_name="product data schema",
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="verbruiksobject_schema",
            field=models.ForeignKey(
                blank=True,
                help_text="JSON schema om het verbruiksobject van een gerelateerd product te valideren.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_typen_verbruiksobject_schemas",
                to="django_json_schema_model.jsonschema",
                verbose_name="verbruiksobject schema",
            ),
        ),
    ]
