# Generated by Django 5.1.4 on 2025-01-09 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_json_schema", "0001_initial"),
        ("producttypen", "0006_alter_producttype_aanmaak_datum_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttype",
            name="verbruiksobject_schema",
            field=models.ForeignKey(
                blank=True,
                help_text="JSON schema om het verbruiksobject van een gerelateerd product te valideren.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_typen",
                to="django_json_schema.jsonschema",
                verbose_name="verbruiksobject schema",
            ),
        ),
    ]
