# Generated by Django 4.2.17 on 2025-02-18 16:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("producttypen", "0006_contentelement_contentelementtranslation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExterneCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "naam",
                    models.CharField(
                        help_text="De naam van het systeem van de externe product code.",
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator("^[^:\\[\\]]+$")
                        ],
                        verbose_name="naam",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="De code van de van het product type in het externe systeem.",
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator("^[^:\\[\\]]+$")
                        ],
                        verbose_name="code",
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        help_text="Het product type waarbij deze externe code hoort.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="externe_codes",
                        to="producttypen.producttype",
                        verbose_name="product type",
                    ),
                ),
            ],
            options={
                "verbose_name": "externe product type code",
                "verbose_name_plural": "externe product type codes",
                "unique_together": {("product_type", "naam")},
            },
        ),
    ]
