# Generated by Django 4.2.17 on 2025-01-20 09:08

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("producttypen", "0006_producttype_verbruiksobject_schema"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentLabel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("naam", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="producttype",
            name="beschrijving",
        ),
        migrations.RemoveField(
            model_name="producttype",
            name="naam",
        ),
        migrations.RemoveField(
            model_name="producttype",
            name="samenvatting",
        ),
        migrations.CreateModel(
            name="ContentElement",
            fields=[
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "label",
                    models.ForeignKey(
                        help_text="Het label van dit content element",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="producttypen.contentlabel",
                        verbose_name="label",
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        help_text="Het product type van dit content element",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_elementen",
                        to="producttypen.producttype",
                        verbose_name="label",
                    ),
                ),
            ],
            options={
                "verbose_name": "content element",
                "verbose_name_plural": "content elementen",
                "ordering": ("product_type", "order"),
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ProductTypeTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                (
                    "samenvatting",
                    models.TextField(
                        default="",
                        help_text="Korte beschrijving van het product type, maximaal 300 karakters.",
                        max_length=300,
                        verbose_name="samenvatting",
                    ),
                ),
                (
                    "naam",
                    models.CharField(
                        help_text="naam van het product type.",
                        max_length=100,
                        verbose_name="product type naam",
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="producttypen.producttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product type Translation",
                "db_table": "producttypen_producttype_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ContentElementTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="De content van dit content element",
                        verbose_name="content",
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="producttypen.contentelement",
                    ),
                ),
            ],
            options={
                "verbose_name": "content element Translation",
                "db_table": "producttypen_contentelement_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
