# Generated by Django 4.2.17 on 2025-02-07 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producttypen", "0006_externecode_eigenschap"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eigenschap",
            name="naam",
            field=models.CharField(
                help_text="De naam van de eigenschap",
                max_length=255,
                validators=[django.core.validators.RegexValidator("^[^:\\[\\]]+$")],
                verbose_name="naam",
            ),
        ),
        migrations.AlterField(
            model_name="eigenschap",
            name="waarde",
            field=models.CharField(
                help_text="De waarde van de eigenschap",
                max_length=255,
                validators=[django.core.validators.RegexValidator("^[^:\\[\\]]+$")],
                verbose_name="waarde",
            ),
        ),
        migrations.AlterField(
            model_name="externecode",
            name="code",
            field=models.CharField(
                help_text="De code van de van het product type in het externe systeem.",
                max_length=255,
                validators=[django.core.validators.RegexValidator("^[^:\\[\\]]+$")],
                verbose_name="code",
            ),
        ),
        migrations.AlterField(
            model_name="externecode",
            name="naam",
            field=models.CharField(
                help_text="De naam van het systeem van de externe product code.",
                max_length=255,
                validators=[django.core.validators.RegexValidator("^[^:\\[\\]]+$")],
                verbose_name="naam",
            ),
        ),
    ]
