# Generated by Django 4.2.19 on 2025-02-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producttypen", "0006_contentelement_contentelementtranslation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttype",
            name="interne_opmerkingen",
            field=models.TextField(
                default="",
                help_text="Interne opmerkingen over het product type.",
                verbose_name="interne opmerkingen",
            ),
        ),
    ]
