# Generated by Django 5.1.4 on 2025-01-09 15:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producttypen", "0007_producttype_verbruiksobject_schema"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentLabel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("naam", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ContentElement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "toelichting",
                    models.TextField(
                        blank=True,
                        help_text="De toelichting van dit content element",
                        null=True,
                        verbose_name="toelichting",
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        help_text="Het product type van dit content element",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_elementen",
                        to="producttypen.producttype",
                        verbose_name="label",
                    ),
                ),
                (
                    "label",
                    models.ForeignKey(
                        help_text="Het label van dit content element",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="producttypen.contentlabel",
                        verbose_name="label",
                    ),
                ),
            ],
            options={
                "verbose_name": "content element",
                "verbose_name_plural": "content elementen",
            },
        ),
        migrations.CreateModel(
            name="ContentElementTekst",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "taalcode",
                    models.CharField(
                        help_text="De taalcode van de content element tekst",
                        max_length=2,
                        verbose_name="taalcode",
                    ),
                ),
                (
                    "content_element",
                    models.ForeignKey(
                        help_text="Het content element van de content element tekst",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teksten",
                        to="producttypen.contentelement",
                        verbose_name="content element",
                    ),
                ),
            ],
            options={
                "verbose_name": "content element tekst",
                "verbose_name_plural": "content element teksten",
            },
        ),
        migrations.CreateModel(
            name="ProductTypeVertaling",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "naam",
                    models.CharField(
                        help_text="naam van het product type.",
                        max_length=100,
                        verbose_name="product type naam",
                    ),
                ),
                (
                    "samenvatting",
                    models.TextField(
                        default="",
                        help_text="Korte beschrijving van het product type, maximaal 300 karakters.",
                        max_length=300,
                        verbose_name="samenvatting",
                    ),
                ),
                (
                    "taalcode",
                    models.CharField(
                        help_text="De taalcode van de product type vertaling",
                        max_length=2,
                        verbose_name="taalcode",
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        help_text="Het product type van de vertaling",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vertalingen",
                        to="producttypen.producttype",
                        verbose_name="label",
                    ),
                ),
            ],
            options={
                "verbose_name": "product type vertaling",
                "verbose_name_plural": "product type vertalingen",
            },
        ),
    ]
