# Generated by Django 4.2.17 on 2025-01-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producttypen", "0007_contentlabel_remove_producttype_beschrijving_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentelement",
            name="label",
        ),
        migrations.AddField(
            model_name="contentelement",
            name="label",
            field=models.ManyToManyField(
                blank=True,
                help_text="De labels van dit content element",
                related_name="content_elements",
                to="producttypen.contentlabel",
                verbose_name="label",
            ),
        ),
    ]
