# Generated by Django 4.2.17 on 2025-01-20 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("producttypen", "0008_remove_contentelement_label_contentelement_label"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contentelement",
            old_name="label",
            new_name="labels",
        ),
    ]
