# Generated by Django 4.2.17 on 2025-03-07 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("producttypen", "0009_parameter"),
    ]

    operations = [
        migrations.CreateModel(
            name="JsonSchema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "naam",
                    models.CharField(
                        help_text="Naam van het json schema.",
                        max_length=200,
                        unique=True,
                        verbose_name="naam",
                    ),
                ),
                (
                    "schema",
                    models.JSONField(
                        help_text="Het schema waartegen gevalideerd kan worden.",
                        verbose_name="schema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Json schema",
                "verbose_name_plural": "Json Schemas",
            },
        ),
        migrations.AddField(
            model_name="producttype",
            name="verbruiksobject_schema",
            field=models.ForeignKey(
                blank=True,
                help_text="JSON schema om het verbruiksobject van een gerelateerd product te valideren.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_typen",
                to="producttypen.jsonschema",
                verbose_name="verbruiksobject schema",
            ),
        ),
    ]
