# Generated by Django 4.2.17 on 2025-01-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producttypen", "0009_rename_label_contentelement_labels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentlabel",
            name="naam",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
