# Generated by Django 4.2.17 on 2025-03-10 16:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("producttypen", "0010_jsonschema_producttype_verbruiksobject_schema"),
    ]

    operations = [
        migrations.CreateModel(
            name="Eigenschap",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "naam",
                    models.CharField(
                        help_text="De naam van de eigenschap.",
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator("^[^:\\[\\]]+$")
                        ],
                        verbose_name="naam",
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        help_text="Het producttype waarbij deze eigenschap hoort.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eigenschappen",
                        to="producttypen.producttype",
                        verbose_name="producttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "eigenschap",
                "verbose_name_plural": "eigenschappen",
                "unique_together": {("product_type", "naam")},
            },
        ),
    ]
