# Generated by Django 4.2.17 on 2025-01-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producttypen", "0010_alter_contentlabel_naam"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentelement",
            name="labels",
            field=models.ManyToManyField(
                blank=True,
                help_text="De labels van dit content element",
                related_name="content_elements",
                to="producttypen.contentlabel",
                verbose_name="labels",
            ),
        ),
    ]
