# Generated by Django 4.2.17 on 2025-01-21 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("producttypen", "0011_alter_contentelement_labels"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Vraag",
        ),
    ]
