# Generated by Django 4.2.17 on 2025-03-28 11:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("producttypen", "0011_producttype_dataobject_schema_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DmnConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "naam",
                    models.CharField(
                        help_text="naam van de dmn instantie.",
                        max_length=255,
                        verbose_name="naam",
                    ),
                ),
                (
                    "tabel_endpoint",
                    models.URLField(
                        help_text="basis endpoint voor de dmn tabellen.",
                        unique=True,
                        verbose_name="url",
                    ),
                ),
            ],
            options={
                "verbose_name": "DMN configuratie",
                "verbose_name_plural": "DMN configuraties",
            },
        ),
        migrations.AlterField(
            model_name="contentelement",
            name="labels",
            field=models.ManyToManyField(
                blank=True,
                help_text="De labels van dit content element",
                related_name="content_elementen",
                to="producttypen.contentlabel",
                verbose_name="labels",
            ),
        ),
        migrations.CreateModel(
            name="PrijsRegel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "beschrijving",
                    models.CharField(
                        help_text="Korte beschrijving van de prijs regel.",
                        max_length=255,
                        verbose_name="beschrijving",
                    ),
                ),
                (
                    "dmn_tabel_id",
                    models.CharField(
                        help_text="id van de dmn tabel binnen de dmn instantie.",
                        max_length=255,
                        verbose_name="dmn tabel id",
                    ),
                ),
                (
                    "dmn_config",
                    models.ForeignKey(
                        help_text="de dmn engine waar de tabel is gedefinieerd.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prijsregels",
                        to="producttypen.dmnconfig",
                        verbose_name="dmn config",
                    ),
                ),
                (
                    "prijs",
                    models.ForeignKey(
                        help_text="De prijs waarbij deze regel hoort.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prijsregels",
                        to="producttypen.prijs",
                        verbose_name="prijs",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prijs regel",
                "verbose_name_plural": "Prijs regels",
            },
        ),
        migrations.CreateModel(
            name="Actie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "naam",
                    models.CharField(
                        help_text="naam van de actie.",
                        max_length=255,
                        verbose_name="naam",
                    ),
                ),
                (
                    "dmn_tabel_id",
                    models.CharField(
                        help_text="id van de dmn tabel binnen de dmn instantie.",
                        max_length=255,
                        verbose_name="dmn tabel id",
                    ),
                ),
                (
                    "dmn_config",
                    models.ForeignKey(
                        help_text="de dmn engine waar de tabel is gedefinieerd.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acties",
                        to="producttypen.dmnconfig",
                        verbose_name="dmn config",
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        help_text="Het producttype waarbij deze actie hoort.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acties",
                        to="producttypen.producttype",
                        verbose_name="Producttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "actie",
                "verbose_name_plural": "acties",
            },
        ),
    ]
