# Generated by Django 4.2.17 on 2025-03-17 15:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("producttypen", "0012_dmnconfig_prijsregel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prijsregel",
            name="dmn_config",
            field=models.ForeignKey(
                help_text="de dmn engine waar de tabel is gedefinieerd.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="producttypen.dmnconfig",
                verbose_name="dmn config",
            ),
        ),
        migrations.CreateModel(
            name="Actie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "dmn_tabel_id",
                    models.CharField(
                        help_text="id van de dmn tabel binnen de dmn instantie.",
                        max_length=255,
                        verbose_name="dmn tabel id",
                    ),
                ),
                (
                    "naam",
                    models.CharField(
                        help_text="naam van de actie.",
                        max_length=255,
                        verbose_name="naam",
                    ),
                ),
                (
                    "dmn_config",
                    models.ForeignKey(
                        help_text="de dmn engine waar de tabel is gedefinieerd.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="producttypen.dmnconfig",
                        verbose_name="dmn config",
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        help_text="Het producttype waarbij deze actie hoort.",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="acties",
                        to="producttypen.producttype",
                        verbose_name="Producttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "actie",
                "verbose_name_plural": "acties",
            },
        ),
    ]
