# Generated by Django 4.2.17 on 2025-03-17 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("producttypen", "0013_alter_prijsregel_dmn_config_actie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentelement",
            name="labels",
            field=models.ManyToManyField(
                blank=True,
                help_text="De labels van dit content element",
                related_name="content_elementen",
                to="producttypen.contentlabel",
                verbose_name="labels",
            ),
        ),
        migrations.AlterField(
            model_name="prijsregel",
            name="dmn_config",
            field=models.ForeignKey(
                help_text="de dmn engine waar de tabel is gedefinieerd.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prijsregels",
                to="producttypen.dmnconfig",
                verbose_name="dmn config",
            ),
        ),
    ]
