# Generated by Django 4.2.17 on 2025-03-25 11:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("producttypen", "0014_alter_contentelement_labels_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExterneVerwijzingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zaaktypen_url",
                    models.URLField(
                        blank=True,
                        help_text="Basis url van zaaktypen.",
                        verbose_name="zaaktypen url",
                    ),
                ),
                (
                    "processen_url",
                    models.URLField(
                        blank=True,
                        help_text="Basis url van processen.",
                        verbose_name="processen url",
                    ),
                ),
                (
                    "verzoektypen_url",
                    models.URLField(
                        blank=True,
                        help_text="Basis url van verzoektypen.",
                        verbose_name="verzoektypen url",
                    ),
                ),
            ],
            options={
                "verbose_name": "ExterneVerwijzing config",
            },
        ),
        migrations.CreateModel(
            name="ZaakType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True,
                        help_text="Uuid van het zaaktype.",
                        null=True,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        help_text="Het product type waarbij dit zaaktype hoort.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zaaktypen",
                        to="producttypen.producttype",
                        verbose_name="product type",
                    ),
                ),
            ],
            options={
                "verbose_name": "zaaktype",
                "verbose_name_plural": "zaaktypen",
                "unique_together": {("product_type", "uuid")},
            },
        ),
        migrations.CreateModel(
            name="VerzoekType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True,
                        help_text="Uuid van het verzoektype.",
                        null=True,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        help_text="Het product type waarbij dit verzoektype hoort.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verzoektypen",
                        to="producttypen.producttype",
                        verbose_name="product type",
                    ),
                ),
            ],
            options={
                "verbose_name": "verzoektype",
                "verbose_name_plural": "verzoektypen",
                "unique_together": {("product_type", "uuid")},
            },
        ),
        migrations.CreateModel(
            name="Proces",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True,
                        help_text="Uuid van het proces.",
                        null=True,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        help_text="Het product type waarbij dit proces hoort.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processen",
                        to="producttypen.producttype",
                        verbose_name="product type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proces",
                "verbose_name_plural": "Processen",
                "unique_together": {("product_type", "uuid")},
            },
        ),
    ]
