# Generated by Django 4.2.17 on 2025-03-21 14:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("producttypen", "0014_alter_contentelement_labels_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZaakType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True,
                        help_text="uuid van het zaaktype",
                        null=True,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        help_text="Het product type waarbij dit zaaktype hoort.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zaaktypen",
                        to="producttypen.producttype",
                        verbose_name="product type",
                    ),
                ),
            ],
            options={
                "verbose_name": "zaaktype",
                "verbose_name_plural": "zaaktypen",
            },
        ),
        migrations.CreateModel(
            name="Proces",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True,
                        help_text="uuid van het proces",
                        null=True,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        help_text="Het product type waarbij dit proces hoort.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processen",
                        to="producttypen.producttype",
                        verbose_name="product type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proces",
                "verbose_name_plural": "Processen",
            },
        ),
    ]
