# Generated by Django 4.2.16 on 2024-11-25 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="filled_email_unique",
        ),
    ]
