# Generated by Django 4.2.13 on 2024-08-07 12:04

import django.db.models.deletion
from django.db import migrations, models

import open_producten.utils.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the object is accessible with the api.",
                        verbose_name="Published",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date the object was created. This field is automatically set.",
                        verbose_name="Created on",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date when the object was last changed. This field is automatically set.",
                        verbose_name="Updated on",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=100, verbose_name="Name"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email address"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=15,
                        validators=[
                            open_producten.utils.validators.validate_phone_number
                        ],
                        verbose_name="Phone number",
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True,
                        help_text="Address street",
                        max_length=250,
                        verbose_name="street",
                    ),
                ),
                (
                    "house_number",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="house number"
                    ),
                ),
                (
                    "postcode",
                    models.CharField(
                        help_text="Address postcode",
                        max_length=7,
                        validators=[
                            open_producten.utils.validators.CustomRegexValidator(
                                message="Invalid postal code.",
                                regex="^[1-9][0-9]{3} ?[a-zA-Z]{2}$",
                            )
                        ],
                        verbose_name="postcode",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="Address city", max_length=250, verbose_name="city"
                    ),
                ),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
            },
        ),
        migrations.CreateModel(
            name="Neighbourhood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Neighbourhood name",
                        max_length=100,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Neighbourhood",
                "verbose_name_plural": "Neighbourhoods",
            },
        ),
        migrations.CreateModel(
            name="OrganisationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Organisation type",
                        max_length=100,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organisation type",
                "verbose_name_plural": "Organisation types",
            },
        ),
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the object is accessible with the api.",
                        verbose_name="Published",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date the object was created. This field is automatically set.",
                        verbose_name="Created on",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date when the object was last changed. This field is automatically set.",
                        verbose_name="Updated on",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=100, verbose_name="Name"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email address"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=15,
                        validators=[
                            open_producten.utils.validators.validate_phone_number
                        ],
                        verbose_name="Phone number",
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True,
                        help_text="Address street",
                        max_length=250,
                        verbose_name="street",
                    ),
                ),
                (
                    "house_number",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="house number"
                    ),
                ),
                (
                    "postcode",
                    models.CharField(
                        help_text="Address postcode",
                        max_length=7,
                        validators=[
                            open_producten.utils.validators.CustomRegexValidator(
                                message="Invalid postal code.",
                                regex="^[1-9][0-9]{3} ?[a-zA-Z]{2}$",
                            )
                        ],
                        verbose_name="postcode",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="Address city", max_length=250, verbose_name="city"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Slug of the organisation",
                        max_length=100,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Logo of the organisation",
                        null=True,
                        upload_to="",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "neighbourhood",
                    models.ForeignKey(
                        blank=True,
                        help_text="The neighbourhood of the organisation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organisation",
                        to="locations.neighbourhood",
                        verbose_name="Neighbourhood",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        help_text="Organisation type",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organisations",
                        to="locations.organisationtype",
                        verbose_name="Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organisation",
                "verbose_name_plural": "Organisations",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="First name of the contact",
                        max_length=255,
                        verbose_name="First name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Last name of the contact",
                        max_length=255,
                        verbose_name="Last name",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="The email address of the contact",
                        max_length=254,
                        verbose_name="Email address",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="The phone number of the contact",
                        max_length=15,
                        validators=[
                            open_producten.utils.validators.validate_phone_number
                        ],
                        verbose_name="Phone number",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        help_text="The role/function of the contact",
                        max_length=100,
                        verbose_name="Rol",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        blank=True,
                        help_text="The organisation of the contact",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_contacts",
                        to="locations.organisation",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
            },
        ),
    ]
