# Generated by Django 4.2.13 on 2024-10-16 12:30

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="coordinates",
            field=django.contrib.gis.db.models.fields.PointField(
                help_text="Geo coordinates of the location",
                srid=4326,
                verbose_name="coordinates",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organisation",
            name="coordinates",
            field=django.contrib.gis.db.models.fields.PointField(
                help_text="Geo coordinates of the location",
                srid=4326,
                verbose_name="coordinates",
            ),
            preserve_default=False,
        ),
    ]
