# Generated by Django 4.2.13 on 2024-09-26 15:46

from django.db import migrations, models
import uuid_utils.compat


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="id",
            field=models.UUIDField(
                default=uuid_utils.compat.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.UUIDField(
                default=uuid_utils.compat.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
