# Generated by Django 5.2.11 on 2026-02-27 11:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producttypen", "0018_actie_direct_url_alter_actie_dmn_config_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttype",
            name="kanalen",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100, unique=True),
                blank=True,
                default=list,
                help_text="Lijst van kanalen per producttype via de API van de referentielijsten",
                size=None,
                verbose_name="kanalen",
            ),
        ),
    ]
