# Generated by Django 4.2.16 on 2024-11-27 14:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import open_producten.utils.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Buurt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "naam",
                    models.CharField(
                        help_text="Naam van de buurt.",
                        max_length=100,
                        unique=True,
                        verbose_name="naam",
                    ),
                ),
            ],
            options={
                "verbose_name": "Buurt",
                "verbose_name_plural": "Buurten",
            },
        ),
        migrations.CreateModel(
            name="Locatie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "naam",
                    models.CharField(blank=True, max_length=100, verbose_name="naam"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email adres"
                    ),
                ),
                (
                    "telefoonnummer",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=15,
                        validators=[
                            open_producten.utils.validators.validate_phone_number
                        ],
                        verbose_name="telefoonnummer",
                    ),
                ),
                (
                    "straat",
                    models.CharField(blank=True, max_length=250, verbose_name="straat"),
                ),
                (
                    "huisnummer",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="huisnummer"
                    ),
                ),
                (
                    "postcode",
                    models.CharField(
                        max_length=7,
                        validators=[
                            open_producten.utils.validators.CustomRegexValidator(
                                message="Invalid postal code.",
                                regex="^[1-9][0-9]{3} ?[a-zA-Z]{2}$",
                            )
                        ],
                        verbose_name="postcode",
                    ),
                ),
                ("stad", models.CharField(max_length=250, verbose_name="stad")),
                (
                    "coordinaten",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="Geo coördinaten van de locatie",
                        srid=4326,
                        verbose_name="coördinaten",
                    ),
                ),
            ],
            options={
                "verbose_name": "Locatie",
                "verbose_name_plural": "Locaties",
            },
        ),
        migrations.CreateModel(
            name="OrganisatieType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "naam",
                    models.CharField(
                        help_text="Naam van het Organisatie type.",
                        max_length=100,
                        unique=True,
                        verbose_name="naam",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organisatie type",
                "verbose_name_plural": "Organisatie typen",
            },
        ),
        migrations.CreateModel(
            name="Organisatie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "naam",
                    models.CharField(blank=True, max_length=100, verbose_name="naam"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email adres"
                    ),
                ),
                (
                    "telefoonnummer",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=15,
                        validators=[
                            open_producten.utils.validators.validate_phone_number
                        ],
                        verbose_name="telefoonnummer",
                    ),
                ),
                (
                    "straat",
                    models.CharField(blank=True, max_length=250, verbose_name="straat"),
                ),
                (
                    "huisnummer",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="huisnummer"
                    ),
                ),
                (
                    "postcode",
                    models.CharField(
                        max_length=7,
                        validators=[
                            open_producten.utils.validators.CustomRegexValidator(
                                message="Invalid postal code.",
                                regex="^[1-9][0-9]{3} ?[a-zA-Z]{2}$",
                            )
                        ],
                        verbose_name="postcode",
                    ),
                ),
                ("stad", models.CharField(max_length=250, verbose_name="stad")),
                (
                    "coordinaten",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="Geo coördinaten van de locatie",
                        srid=4326,
                        verbose_name="coördinaten",
                    ),
                ),
                (
                    "buurt",
                    models.ForeignKey(
                        blank=True,
                        help_text="De Buurt waarin organisatie actief is",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organisaties",
                        to="locaties.buurt",
                        verbose_name="Buurt",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        help_text="Organisatie type",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organisaties",
                        to="locaties.organisatietype",
                        verbose_name="Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organisatie",
                "verbose_name_plural": "Organisaties",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "voornaam",
                    models.CharField(
                        help_text="voornaam van het contact",
                        max_length=255,
                        verbose_name="voornaam",
                    ),
                ),
                (
                    "achternaam",
                    models.CharField(
                        help_text="achternaam van het contact",
                        max_length=255,
                        verbose_name="achternaam",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="email van het contact",
                        max_length=254,
                        verbose_name="email adres",
                    ),
                ),
                (
                    "telefoonnummer",
                    models.CharField(
                        blank=True,
                        help_text="telefoonnummer van het contact",
                        max_length=15,
                        validators=[
                            open_producten.utils.validators.validate_phone_number
                        ],
                        verbose_name="telefoonnummer",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        blank=True,
                        help_text="De rol/functie van het contact",
                        max_length=100,
                        verbose_name="rol",
                    ),
                ),
                (
                    "organisatie",
                    models.ForeignKey(
                        blank=True,
                        help_text="De organisatie van het contact",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_contacten",
                        to="locaties.organisatie",
                        verbose_name="organisatie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacten",
            },
        ),
    ]
