# Generated by Django 4.2.16 on 2024-11-28 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locaties", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organisatie",
            name="buurt",
        ),
        migrations.RemoveField(
            model_name="organisatie",
            name="type",
        ),
        migrations.DeleteModel(
            name="Buurt",
        ),
        migrations.DeleteModel(
            name="OrganisatieType",
        ),
    ]
