# Generated by Django 4.2.17 on 2024-12-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locaties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisatie",
            name="code",
            field=models.CharField(
                help_text="code van de organisatie.",
                max_length=100,
                unique=True,
                verbose_name="code",
            ),
        ),
    ]
