# Generated by Django 4.2.17 on 2025-01-02 10:12

from django.db import migrations, models
import open_producten.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("locaties", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locatie",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="email adres"
            ),
        ),
        migrations.AlterField(
            model_name="locatie",
            name="huisnummer",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="huisnummer"
            ),
        ),
        migrations.AlterField(
            model_name="locatie",
            name="naam",
            field=models.CharField(max_length=100, verbose_name="naam"),
        ),
        migrations.AlterField(
            model_name="locatie",
            name="postcode",
            field=models.CharField(
                blank=True,
                max_length=7,
                null=True,
                validators=[
                    open_producten.utils.validators.CustomRegexValidator(
                        message="Invalid postal code.",
                        regex="^[1-9][0-9]{3} ?[a-zA-Z]{2}$",
                    )
                ],
                verbose_name="postcode",
            ),
        ),
        migrations.AlterField(
            model_name="locatie",
            name="stad",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="stad"
            ),
        ),
        migrations.AlterField(
            model_name="locatie",
            name="straat",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="straat"
            ),
        ),
        migrations.AlterField(
            model_name="locatie",
            name="telefoonnummer",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[open_producten.utils.validators.validate_phone_number],
                verbose_name="telefoonnummer",
            ),
        ),
        migrations.AlterField(
            model_name="organisatie",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="email adres"
            ),
        ),
        migrations.AlterField(
            model_name="organisatie",
            name="huisnummer",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="huisnummer"
            ),
        ),
        migrations.AlterField(
            model_name="organisatie",
            name="naam",
            field=models.CharField(max_length=100, verbose_name="naam"),
        ),
        migrations.AlterField(
            model_name="organisatie",
            name="postcode",
            field=models.CharField(
                blank=True,
                max_length=7,
                null=True,
                validators=[
                    open_producten.utils.validators.CustomRegexValidator(
                        message="Invalid postal code.",
                        regex="^[1-9][0-9]{3} ?[a-zA-Z]{2}$",
                    )
                ],
                verbose_name="postcode",
            ),
        ),
        migrations.AlterField(
            model_name="organisatie",
            name="stad",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="stad"
            ),
        ),
        migrations.AlterField(
            model_name="organisatie",
            name="straat",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="straat"
            ),
        ),
        migrations.AlterField(
            model_name="organisatie",
            name="telefoonnummer",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[open_producten.utils.validators.validate_phone_number],
                verbose_name="telefoonnummer",
            ),
        ),
    ]
