# Generated by Django 4.2.17 on 2025-01-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locaties", "0002_alter_locatie_email_alter_locatie_huisnummer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisatie",
            name="code",
            field=models.CharField(
                help_text="code van de organisatie.",
                max_length=100,
                unique=True,
                verbose_name="code",
            ),
        ),
    ]
