# Generated by Django 4.2.17 on 2025-01-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locaties", "0003_organisatie_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locatie",
            name="huisnummer",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="huisnummer"
            ),
        ),
        migrations.AlterField(
            model_name="locatie",
            name="naam",
            field=models.CharField(max_length=255, verbose_name="naam"),
        ),
        migrations.AlterField(
            model_name="locatie",
            name="stad",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="stad"
            ),
        ),
        migrations.AlterField(
            model_name="locatie",
            name="straat",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="straat"
            ),
        ),
        migrations.AlterField(
            model_name="organisatie",
            name="code",
            field=models.CharField(
                help_text="code van de organisatie.",
                max_length=255,
                unique=True,
                verbose_name="code",
            ),
        ),
        migrations.AlterField(
            model_name="organisatie",
            name="huisnummer",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="huisnummer"
            ),
        ),
        migrations.AlterField(
            model_name="organisatie",
            name="naam",
            field=models.CharField(max_length=255, verbose_name="naam"),
        ),
        migrations.AlterField(
            model_name="organisatie",
            name="stad",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="stad"
            ),
        ),
        migrations.AlterField(
            model_name="organisatie",
            name="straat",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="straat"
            ),
        ),
    ]
