# Generated by Django 4.2.17 on 2025-03-10 14:08

from django.db import migrations, models
import open_producten.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("locaties", "0005_alter_locatie_postcode_alter_organisatie_postcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locatie",
            name="postcode",
            field=models.CharField(
                blank=True,
                max_length=7,
                null=True,
                validators=[
                    open_producten.utils.validators.CustomRegexValidator(
                        message="Invalid postal code (spaces are not allowed).",
                        regex="^[1-9][0-9]{3} [A-Z]{2}$",
                    )
                ],
                verbose_name="postcode",
            ),
        ),
        migrations.AlterField(
            model_name="organisatie",
            name="postcode",
            field=models.CharField(
                blank=True,
                max_length=7,
                null=True,
                validators=[
                    open_producten.utils.validators.CustomRegexValidator(
                        message="Invalid postal code (spaces are not allowed).",
                        regex="^[1-9][0-9]{3} [A-Z]{2}$",
                    )
                ],
                verbose_name="postcode",
            ),
        ),
    ]
