# Generated by Django 4.2.13 on 2024-07-10 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("producttypes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                (
                    "published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the object is accessible with the api.",
                        verbose_name="Published",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date the object was created. This field is automatically set.",
                        verbose_name="Created on",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date when the object was last changed. This field is automatically set.",
                        verbose_name="Updated on",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the category",
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Slug of the category",
                        max_length=100,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Description of the category",
                        verbose_name="Description",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        help_text="Icon of the category",
                        null=True,
                        upload_to="",
                        verbose_name="Icon",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Image of the category",
                        null=True,
                        upload_to="",
                        verbose_name="Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ("path",),
            },
        ),
        migrations.AlterField(
            model_name="producttype",
            name="conditions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Conditions applicable for the product type",
                related_name="product_types",
                to="producttypes.condition",
                verbose_name="Conditions",
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tags which the product is linked to",
                related_name="product_types",
                to="producttypes.tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="uniform_product_name",
            field=models.ForeignKey(
                help_text="Uniform product name defined by Dutch gov",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_types",
                to="producttypes.upn",
                verbose_name="Uniform Product name",
            ),
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=250, verbose_name="Vraag")),
                ("answer", models.TextField(verbose_name="Antwoord")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="producttypes.category",
                        verbose_name="Category",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="producttypes.producttype",
                        verbose_name="Product type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vraag",
                "verbose_name_plural": "FAQ vragen",
            },
        ),
        migrations.CreateModel(
            name="CategoryProductType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="producttypes.category",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="producttypes.producttype",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="producttype",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Categories which the product is linked to",
                related_name="product_types",
                through="producttypes.CategoryProductType",
                to="producttypes.category",
                verbose_name="Categories",
            ),
        ),
    ]
