# Generated by Django 4.2.13 on 2024-08-09 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("producttypes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="condition",
            name="rule",
        ),
        migrations.AlterField(
            model_name="field",
            name="description",
            field=models.TextField(
                help_text="Short description of the field",
                max_length=300,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="name",
            field=models.CharField(
                help_text="The name of the field", max_length=255, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="price",
            name="product_type",
            field=models.ForeignKey(
                help_text="The product type that this price belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prices",
                to="producttypes.producttype",
                verbose_name="Product type",
            ),
        ),
        migrations.AlterField(
            model_name="priceoption",
            name="description",
            field=models.CharField(
                help_text="Short description of the option",
                max_length=100,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="priceoption",
            name="price",
            field=models.ForeignKey(
                help_text="The price this option belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="producttypes.price",
                verbose_name="Price",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="price",
            unique_together={("product_type", "valid_from")},
        ),
    ]
