# Generated by Django 4.2.13 on 2024-08-09 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("producttypes", "0002_remove_condition_rule_alter_field_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="producttypes.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="product_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="producttypes.producttype",
                verbose_name="Product type",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="type",
            field=models.ForeignKey(
                help_text="The related tag type",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="tags",
                to="producttypes.tagtype",
                verbose_name="Type",
            ),
        ),
    ]
