# Generated by Django 4.2.13 on 2024-07-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "producttypes",
            "0003_alter_question_options_alter_field_product_type_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="categoryproducttype",
            old_name="product",
            new_name="product_type",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="product",
            new_name="product_type",
        ),
        migrations.AlterField(
            model_name="producttype",
            name="name",
            field=models.CharField(
                help_text="Name of the product type",
                max_length=100,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="slug",
            field=models.SlugField(
                help_text="Slug of the product type",
                max_length=100,
                unique=True,
                verbose_name="Slug",
            ),
        ),
    ]
