# Generated by Django 4.2.13 on 2024-08-09 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "producttypes",
            "0003_alter_question_category_alter_question_product_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name="categoryproducttype",
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name="question",
            order_with_respect_to=None,
        ),
    ]
