# Generated by Django 4.2.13 on 2024-08-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
        ("producttypes", "0005_remove_condition_rule_alter_field_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttype",
            name="contacts",
            field=models.ManyToManyField(
                blank=True,
                help_text="The contacts responsible for the product",
                related_name="products",
                to="locations.contact",
                verbose_name="Product contacts",
            ),
        ),
        migrations.AddField(
            model_name="producttype",
            name="locations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Locations where the product is available at.",
                related_name="products",
                to="locations.location",
                verbose_name="Product locations",
            ),
        ),
        migrations.AddField(
            model_name="producttype",
            name="organisations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Organisations which provides this product",
                related_name="products",
                to="locations.organisation",
                verbose_name="Organisations",
            ),
        ),
    ]
