# Generated by Django 4.2.13 on 2024-10-11 08:07

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("producttypes", "0006_remove_uniformproductname_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=tinymce.models.HTMLField(
                blank=True,
                default="",
                help_text="Description of the category",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="condition",
            name="negative_text",
            field=tinymce.models.HTMLField(
                help_text="Description how not to meet the condition",
                verbose_name="Negative text",
            ),
        ),
        migrations.AlterField(
            model_name="condition",
            name="positive_text",
            field=tinymce.models.HTMLField(
                help_text="Description how to meet the condition",
                verbose_name="Positive text",
            ),
        ),
        migrations.AlterField(
            model_name="condition",
            name="question",
            field=tinymce.models.HTMLField(
                help_text="Question used in the question-answer game",
                verbose_name="Question",
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="description",
            field=tinymce.models.HTMLField(
                help_text="Short description of the field",
                max_length=300,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="content",
            field=tinymce.models.HTMLField(
                help_text="Product type content with build-in WYSIWYG editor.",
                verbose_name="Content",
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="summary",
            field=tinymce.models.HTMLField(
                default="",
                help_text="Short description of the product type, limited to 300 characters.",
                max_length=300,
                verbose_name="Summary",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer",
            field=tinymce.models.HTMLField(verbose_name="Answer"),
        ),
    ]
