# Generated by Django 4.2.17 on 2024-12-27 19:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import open_producten.producten.models.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("producttypen", "0004_producttype_contacten_producttype_locaties_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "gepubliceerd",
                    models.BooleanField(
                        default=False,
                        help_text="Geeft aan of het object getoond kan worden.",
                        verbose_name="gepubliceerd",
                    ),
                ),
                (
                    "aanmaak_datum",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="De datum waarop het object is aangemaakt.",
                        verbose_name="Created on",
                    ),
                ),
                (
                    "update_datum",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="De datum waarop het object voor het laatst is gewijzigd.",
                        verbose_name="Updated on",
                    ),
                ),
                (
                    "start_datum",
                    models.DateField(
                        help_text="De start datum van dit product.",
                        verbose_name="start datum",
                    ),
                ),
                (
                    "eind_datum",
                    models.DateField(
                        help_text="De einddatum van dit product.",
                        verbose_name="eind datum",
                    ),
                ),
                (
                    "bsn",
                    models.CharField(
                        blank=True,
                        help_text="De BSN van de product eigenaar, BSN van 8 karakters moet met een extra 0 beginnen.",
                        null=True,
                        validators=[
                            open_producten.producten.models.validators.validate_bsn
                        ],
                        verbose_name="BSN",
                    ),
                ),
                (
                    "kvk",
                    models.CharField(
                        blank=True,
                        help_text="Het kvk nummer van de product eigenaar",
                        max_length=8,
                        null=True,
                        validators=[
                            django.core.validators.MinLengthValidator(8),
                            django.core.validators.RegexValidator("^[0-9]*$"),
                        ],
                        verbose_name="KVK nummer",
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        help_text="Het type van dit product",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="producten",
                        to="producttypen.producttype",
                        verbose_name="Product type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Producten",
            },
        ),
    ]
