# Generated by Django 4.2.17 on 2025-01-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="eind_datum",
            field=models.DateField(
                blank=True,
                help_text="De einddatum van dit product.",
                null=True,
                verbose_name="eind datum",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="start_datum",
            field=models.DateField(
                blank=True,
                help_text="De start datum van dit product.",
                null=True,
                verbose_name="start datum",
            ),
        ),
    ]
