# Generated by Django 4.2.17 on 2024-12-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                blank=True,
                help_text="Status van dit product.",
                null=True,
                verbose_name="status",
            ),
        ),
    ]
