# Generated by Django 4.2.17 on 2024-12-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0002_product_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                blank=True,
                help_text="De status opties worden bepaald door het veld 'toegestane statussen' van het gerelateerde product type.",
                null=True,
                verbose_name="status",
            ),
        ),
    ]
