# Generated by Django 4.2.17 on 2025-01-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0002_alter_product_eind_datum_alter_product_start_datum"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("initieel", "Initieel"),
                    ("gereed", "Gereed"),
                    ("actief", "Actief"),
                    ("ingetrokken", "Ingetrokken"),
                    ("geweigerd", "Geweigerd"),
                    ("verlopen", "Verlopen"),
                ],
                default="initieel",
                help_text="De status opties worden bepaald door het veld 'toegestane statussen' van het gerelateerde product type.",
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="aanmaak_datum",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="De datum waarop het object is aangemaakt.",
                verbose_name="aanmaak datum",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="eind_datum",
            field=models.DateField(
                blank=True,
                help_text="De einddatum van dit product. Op deze datum zal de status van het product automatisch naar VERLOPEN worden gezet. Op het moment dat de eind_datum wordt ingevuld moet de status VERLOPEN op het product type zijn toegestaan.",
                null=True,
                verbose_name="eind datum",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="start_datum",
            field=models.DateField(
                blank=True,
                help_text="De start datum van dit product. Op deze datum zal de status van het product automatisch naar ACTIEF worden gezet. Op het moment dat de start_datum wordt ingevuld moet de status ACTIEF op het product type zijn toegestaan.",
                null=True,
                verbose_name="start datum",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="update_datum",
            field=models.DateTimeField(
                auto_now=True,
                help_text="De datum waarop het object voor het laatst is gewijzigd.",
                verbose_name="update datum",
            ),
        ),
    ]
