# Generated by Django 4.2.17 on 2025-01-29 10:26

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0003_product_status_alter_product_aanmaak_datum_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="frequentie",
            field=models.CharField(
                choices=[
                    ("eenmalig", "Eenmalig"),
                    ("maandelijks", "Maandelijks"),
                    ("jaarlijks", "Jaarlijks"),
                ],
                default="eenmalig",
                help_text="De frequentie van betalingen.",
                max_length=30,
                verbose_name="Prijs frequentie",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="prijs",
            field=models.DecimalField(
                decimal_places=2,
                default="0.01",
                help_text="De prijs van het product.",
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="bedrag",
            ),
            preserve_default=False,
        ),
    ]
