# Generated by Django 4.2.17 on 2024-12-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0003_alter_product_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("initieel", "Initieel"),
                    ("gereed", "Gereed"),
                    ("actief", "Actief"),
                    ("ingetrokken", "Ingetrokken"),
                    ("geweigerd", "Geweigerd"),
                    ("verlopen", "Verlopen"),
                ],
                default="initieel",
                help_text="De status opties worden bepaald door het veld 'toegestane statussen' van het gerelateerde product type.",
                verbose_name="status",
            ),
        ),
    ]
