# Generated by Django 4.2.17 on 2025-01-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0003_product_status_alter_product_aanmaak_datum_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="verbruiksobject",
            field=models.JSONField(
                blank=True,
                help_text="Verbruiksobject van dit product. Wordt gevalideerd met het `verbruiksobject_schema` uit het product type.",
                null=True,
                verbose_name="verbruiksobject",
            ),
        ),
    ]
