# Generated by Django 4.2.17 on 2025-03-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0004_product_frequentie_product_prijs"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="verbruiksobject",
            field=models.JSONField(
                blank=True,
                help_text="Verbruiksobject van dit product. Wordt gevalideerd met het `verbruiksobject_schema` uit het product type.",
                null=True,
                verbose_name="verbruiksobject",
            ),
        ),
    ]
