# Generated by Django 4.2.17 on 2025-01-03 14:09

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0004_alter_product_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="eind_datum",
            field=models.DateField(
                blank=True,
                help_text="De einddatum van dit product. Op deze datum zal de status van het product automatisch naar VERLOPEN worden gezet",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(datetime.date.today)
                ],
                verbose_name="eind datum",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="start_datum",
            field=models.DateField(
                blank=True,
                help_text="De start datum van dit product. Op deze datum zal de status van het product automatisch naar ACTIEF worden gezet",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(datetime.date.today)
                ],
                verbose_name="start datum",
            ),
        ),
    ]
