# Generated by Django 4.2.17 on 2025-03-10 16:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("producttypen", "0011_eigenschap"),
        ("producten", "0005_product_verbruiksobject"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductEigenschap",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "waarde",
                    models.CharField(
                        help_text="De waarde van de eigenschap.",
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator("^[^:\\[\\]]+$")
                        ],
                        verbose_name="waarde",
                    ),
                ),
                (
                    "eigenschap",
                    models.ForeignKey(
                        help_text="Het eigenschap waarbij deze waarde hoort.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waardes",
                        to="producttypen.eigenschap",
                        verbose_name="producttype",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Het product waarbij deze eigenschap hoort.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eigenschappen",
                        to="producten.product",
                        verbose_name="producttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "product eigenschap",
                "verbose_name_plural": "product eigenschappen",
                "unique_together": {("product", "eigenschap")},
            },
        ),
    ]
