# Generated by Django 4.2.17 on 2025-01-09 09:49

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0005_alter_product_eind_datum_alter_product_start_datum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="eind_datum",
            field=models.DateField(
                blank=True,
                help_text="De einddatum van dit product. Op deze datum zal de status van het product automatisch naar VERLOPEN worden gezet. Op het moment dat de eind_datum wordt ingevuld moet de status VERLOPEN op het product type zijn toegestaan.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(datetime.date.today)
                ],
                verbose_name="eind datum",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="start_datum",
            field=models.DateField(
                blank=True,
                help_text="De start datum van dit product. Op deze datum zal de status van het product automatisch naar ACTIEF worden gezet. Op het moment dat de start_datum wordt ingevuld moet de status ACTIEF op het product type zijn toegestaan.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(datetime.date.today)
                ],
                verbose_name="start datum",
            ),
        ),
    ]
