# Generated by Django 4.2.17 on 2025-03-28 11:23

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "producttypen",
            "0012_dmnconfig_alter_contentelement_labels_prijsregel_and_more",
        ),
        ("producten", "0007_add_product_eigenaar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="prijs",
            field=models.DecimalField(
                decimal_places=2,
                help_text="De prijs van het product.",
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="prijs",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.ForeignKey(
                help_text="Het type van dit product",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="producten",
                to="producttypen.producttype",
                verbose_name="Product type",
            ),
        ),
    ]
