# Generated by Django 5.1.4 on 2025-01-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0008_alter_product_eind_datum_alter_product_start_datum"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="verbruiksobject",
            field=models.JSONField(
                blank=True,
                help_text="Verbruiksobject van dit product. Wordt gevalideerd met het `verbruiksobject_schema` uit het product type.",
                null=True,
                verbose_name="verbruiksobject",
            ),
        ),
    ]
