# Generated by Django 4.2.17 on 2025-03-28 15:42

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0008_alter_product_prijs_alter_product_product_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="dataobject",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="Dataobject van dit product. Wordt gevalideerd met het `dataobject_schema` uit het product type.",
                null=True,
                verbose_name="dataobject",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="verbruiksobject",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="Verbruiksobject van dit product. Wordt gevalideerd met het `verbruiksobject_schema` uit het product type.",
                null=True,
                verbose_name="verbruiksobject",
            ),
        ),
    ]
